### ISSUE TITLE
我只有一个4060gpu，请问我应该如何使用预训练模型生成模型呢？

### ISSUE THREAD

**Issue by jirouhanjinlun** [octree-nn/octfusion#5]
如题，我不知道如何修改代码使其由原本的4个gpu变成适配单个gpu的代码使其能在我的设备上运行

**Comment by wst2001** [comment]
您好！可以修改shell文件中的gpu_ids=0和NGPU=1，改为单卡运行，如下所示：
### set gpus ###
gpu_ids=0       # multi-gpu

if [ ${#gpu_ids} -gt 1 ]; then
    # specify these two if multi-gpu
    NGPU=1
    HOST_NODE_ADDR="localhost:25000"
    echo "HERE"
fi

**Comment by jirouhanjinlun** [comment]
> 您好！可以修改shell文件中的gpu_ids=0和NGPU=1，改为单卡运行，如下所示： gpu_ids=0 # multi-gpu
> 
> if [ ${#gpu_ids} -gt 1 ]; then # specify these two if multi-gpu NGPU=1 HOST_NODE_ADDR="localhost:25000" echo "HERE" fi

您好，在按照您的意见修改代码后运行得到以下结果，没有其他输出了，，请问这是正常的吗？
<img width="1013" alt="df0f3e21e2b28088d86f7e8991c4824" src="https://github.com/user-attachments/assets/5259890f-f247-4b65-a0ad-5be942999bfb">

**Comment by wst2001** [comment]
在我的环境下这个shell文件可以正常运行。由于程序没有错误信息直接结束，我猜测可能不是代码问题而是系统报错，比如系统的运行内存不足时可能会直接kill程序。可以尝试检查一下系统的log有没有相关错误信息。

**Comment by qsh624** [comment]
@jirouhanjinlun 想请问您在4060上最后训练成功了嘛
