### ISSUE TITLE
Sketch reconstruction

### ISSUE THREAD

**Issue by XztOK** [octree-nn/octfusion#7]
Hello author, I'm very much supposed to be interested in your work, especially about the generation of 3D models under sketch conditions. Can you provide me with the specific code for this, please?

**Comment by wst2001** [comment]
Thank you! Code for sketch-condition generation will be released soon. We add sketch-condition attention in our low-resolution network following LAS-Diffusion. The code and data processing are exactly the same.

**Comment by XztOK** [comment]
> Thank you! Code for sketch-condition generation will be released soon. We add sketch-condition attention in our low-resolution network following LAS-Diffusion. The code and data processing are exactly the same.

Thank you!  I was wondering if the whole model can be trained on a single 4090?

**Comment by wst2001** [comment]
I think it's OK to trained on single 4090. Our single-category generation experiment(second stage) was trained on two 4090 GPUs for 500 epochs, taking about 2-3 days.

**Comment by FeiiYin** [comment]
Hi, I am really impressed by your work, will it be ok for you to share the code and checkpoint of sketch-conditioned diffusion network? That would be really helpful!

**Comment by qsh624** [comment]
@FeiiYin Hello, I'm also very interested in the work of the sketch conditional diffusion network part. May I ask if you have made any progress now?
